### ISSUE TITLE
5. Building Block View

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/radarin_en1a#10]

**Comment by Elias-Llera** [comment]
Cómo documentar la sección: https://docs.arc42.org/section-5/

**Comment by Elias-Llera** [comment]
Adjunto dos imágenes con los esquemas de nivel 1 y 2 para el punto 5 de la documentación. Si os parece, echadle un ojo rápido a ver si se os ocurre algún cambio que se pueda hacer antes de crear los esquemas en la documentación.

![punto 5 documentacion level1](https://user-images.githubusercontent.com/60401209/108241117-c82fe500-714b-11eb-97d7-dee003d6c24f.jpg)
![punto 5 documentacion level2](https://user-images.githubusercontent.com/60401209/108241124-c82fe500-714b-11eb-8a09-76e8cf67722b.jpg)

**Comment by UO264817** [comment]
![05_building_blocks-EN](https://user-images.githubusercontent.com/71762070/116938511-2bb9b100-ac6b-11eb-9242-ba9db1de7faf.png)
