### ISSUE TITLE
6. Runtime View

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/radarin_en1a#11]
To assign

**Comment by Elias-Llera** [comment]
Cómo documentar la sección: https://docs.arc42.org/section-6/

**Comment by UO264817** [comment]
I have a small for idea the runtime view, but If someone wants to add something feel free to do so:
Changing your current location:
Alice - Moves -> Radarin - requests a location update -> Alice's pod -> updates the location

Checking someone else's location
Bob - Check's Alice location -> Radarin - checks if the location for bob is been updated ->Alice's pod
If it's been updated:
Alice's pod - sends the updated information -> Radarin -> updates the location for Alice on Bob's local DB and displays it
Else:
Alice's pod - sends a message telling Radarin that it's information is up to date -> Radarin -> Displays Alice's current location

I don't know if I should add any other use case.

**Comment by Elias-Llera** [comment]
Those are good examples. Maybe we can also add something like
Alice - checks for nearby friends -> radarin - checks DB for recent locations -> radarin -> updates map with those locations
Or something close to that.
Also, maybe a use case related to adding a friend or notifying that a friend has updated its position

**Comment by JairoGC-1812** [comment]
After a thorough team review we consider this matter completed
