### ISSUE TITLE
Problems with the privacy of radarin folder and files from SOLID pod.

### ISSUE THREAD

**Issue by sergady** [Arquisoft/radarin_en1a#32]
Currently, when working with the pod, we have the privacy settings of the radarin folder (the one that contains all the information we use on the app) on "Editor" for everyone. 

This is obviously an important issue of the app considering the security. We have an idea of the problem but not yet the solution.

**Comment by JairoGC-1812** [comment]
Besides this problem, the app cannot read files even though the user is authenticated and the privacy settings are correct. E.g: I can read Francisco's files from my browser but the app gives and "Unauthenticated" error

**Comment by UO264817** [comment]
Solved, the issue was because we were using the regular fetch function, when we should have used the solid.auth.fetch version.
