### ISSUE TITLE
Difference between markers sizes.

### ISSUE THREAD

**Issue by sergady** [Arquisoft/radarin_en1a#33]
The markers that show the position of the user and the markers that show the friends have a difference in size. When you zoom out or in, the user marker scales but the friends don't. 

It is a low severity issue.

**Comment by Diecaal** [comment]
This can be obtained using the scaledSize property, inside the icon property on Google Marker component. We used the object provided by google maps, Size: 
`icon={{ url: ... , scaledSize: new window.google.maps.Size(20, 20) }} `
