### ISSUE TITLE
Update the documentation to reflect the dessign changes of the application

### ISSUE THREAD

**Issue by UO264817** [Arquisoft/radarin_en1a#40]
The aplication doesn't use a database, nor a REST api. This dessign choice was made to increase the user's control over their privacy, so they could have more control over who can see their location (maybe you don't want all your solid friends to see your location, or maybe you can make your own code to show different people different locations, that's anyone's business.)
We have to reflect those changes on the documentation.

**Comment by sergady** [comment]
I added some design decisions to the doc 9.

**Comment by sergady** [comment]
I added some terms and the design of the doc 12.

**Comment by JairoGC-1812** [comment]
I wrote localy some paragraphs for the doc 9, but didn't upload it because it appears as "TO DO". Maybe Sergio forgot to commit it? Anyway I keep it in local just in case it interferes in any way

**Comment by JairoGC-1812** [comment]
After the problem was solved I included my part of the update in Doc 9

**Comment by sergady** [comment]
We should write down the decision made about the admin role not being used.

**Comment by JairoGC-1812** [comment]
All updates have been made
