### ISSUE TITLE
Hide friends list when "offline"

### ISSUE THREAD

**Issue by UO264817** [Arquisoft/radarin_en1a#64]
Should be an easy fix, just add a check for the "online" constant

**Comment by sergady** [comment]
Improved but not finished in cdff39db33b7b111b55bf8b73b66f291c67ed702

**Comment by sergady** [comment]
After meeting with Fran and chatting about this topic, we found out that it was not explained carefully and I misunderstood the intention. I commited some small changes (44c0170a7be70bb2075b38b6517f0becbf7317b7) and now Fran is going to finish this issue.

**Comment by sergady** [comment]
Now, the friends state is showed by color on his name:
- Green: online
- Grey: offline
