### ISSUE TITLE
Discuss and write conclusions related to Admin role

### ISSUE THREAD

**Issue by JairoGC-1812** [Arquisoft/radarin_en1a#68]
So far an admin role is not implemented, even though it is in the requirements. We should discuss this matter and write and argument our conclusions

**Comment by sergady** [comment]
We should explain that each user is the admin of their own data, then not needing an admin on the app.

**Comment by UO264817** [comment]
Closed because it will be part of the presentation and the documentation, that are already opened issues

**Comment by JairoGC-1812** [comment]
Reopened because even if it is part of the documentation it is not evident nor redundant

**Comment by sergady** [comment]
We decided it and now it's written on the documentation.
