### ISSUE TITLE
Fix github actions deployment

### ISSUE THREAD

**Issue by sergady** [Arquisoft/radarin_en1a#69]
We should clean all the warnings in the code so the github actions deployment works without problem.

**Comment by sergady** [comment]
src/App.js
  Line 64:23:  Expected '!==' and instead saw '!='           eqeqeq
  Line 217:5:  Do not mutate state directly. Use setState()  react/no-direct-mutation-state
  Line 218:5:  Do not mutate state directly. Use setState()  react/no-direct-mutation-state

src/components/FriendList.js
  Line 4:5:    Useless constructor                                                                                                                          no-useless-constructor
  Line 16:27:  Expected '===' and instead saw '=='                                                                                                          eqeqeq
  Line 20:28:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images                                    jsx-a11y/alt-text
  Line 20:74:  Using target="_blank" without rel="noreferrer" is a security risk: see https://html.spec.whatwg.org/multipage/links.html#link-type-noopener  react/jsx-no-target-blank

src/components/Map.js
  Line 77:34:  Array.prototype.map() expects a return value from arrow function  array-callback-return

Fixed errors but one in the Map.js. As this part was mainly developed by @Diecaal , I will let him fix the last warning regarding the map.

The errors are fixed in the commit: https://github.com/Arquisoft/radarin_en1a/commit/730ef9d4f2aba15bdb0b812f206e94bd1be1dc84

**Comment by Diecaal** [comment]
Following warning:
src/components/Map.js
Line 77:34: Array.prototype.map() expects a return value from arrow function array-callback-return
Fixed in commit: https://github.com/Arquisoft/radarin_en1a/commit/cd62a956ee229dccf98b9214f693a973de33b601
