### ISSUE TITLE
4. Solution Strategy

### ISSUE THREAD

**Issue by Elias-Llera** [Arquisoft/radarin_en1a#9]
To assign

**Comment by Elias-Llera** [comment]
Cómo documentar la sección: https://docs.arc42.org/section-4/

**Comment by Elias-Llera** [comment]
Adjunto archivo txt con el borrador de la información a añadir a la documentación. Si no os importa, echadle un ojo rápido para ver si falta/sobra algo muy obvio para poder tener todos los puntos claros antes de redactarlo en la documentación.

[punto 4 documentacion.txt](https://github.com/Arquisoft/radarin_en1a/files/5997340/punto.4.documentacion.txt)

**Comment by JairoGC-1812** [comment]
After a thorough team review we consider this matter completed
